### ISSUE TITLE
WSL Support

### ISSUE THREAD

**Issue by Ventajou** [danielgjackson/vscode-auto-dark-mode-windows#3]
Hi! Thanks for the extension!

I do most of my work in WSL and I use the Remote - WSL extension from Microsoft to work on them. VS Code wants to install this extension on the WSL side, which keeps it from working. Is there a way to ensure it always runs on Windows proper?

**Comment by danielgjackson** [comment]
Hi Ventajou,

Glad you enjoy the extension!

The `package.json` did specify `"extensionKind": "ui"`, and this is supposed to indicate that it should run in the UI-side, and not remotely.  According to the [Remote Extension documentation](https://code.visualstudio.com/api/advanced-topics/remote-extensions#incorrect-execution-location), since VS Code 1.40, they've made this field an array, yet the old string value of `"ui"` maps to `["ui", "workspace"]`, so I would've expected it to work... but it didn't!

I've now changed it to an array `["ui"]`, and it seems to work for me.

So, please check for extension updates, update the extension, and reload.

Let me know if it doesn't work for you and I can reopen this issue.

Cheers!

Dan

**Comment by Ventajou** [comment]
wow, really quick turnaround! it works great, thanks!
